//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANdotNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string MaGiaoDich { get; set; }
        public string IDNguoiDung { get; set; }
        public string IDDoXe { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDienThoai { get; set; }
        public string BienSoXe { get; set; }
        public string MaLoaiXe { get; set; }
        public System.DateTime ThoiGianVao { get; set; }
        public Nullable<System.DateTime> ThoiGianRa { get; set; }
        public decimal ThanhTien { get; set; }
        public string HinhAnhVao { get; set; }
        public string HinhAnhRa { get; set; }
    
        public virtual LoaiXe LoaiXe { get; set; }
        public virtual User User { get; set; }
    }
}
